<?php // This is DGE //
wfLoadExtensions( [
	'AbuseFilter',
	'CategoryTree',
	'CentralAuth',
	'CentralNotice',
	'CharInsert',
	'Cite',
	'CiteThisPage',
	'CirrusSearch',
	'CodeEditor',
	'ConfirmEdit',
	'CommonsMetadata',
	'DismissableSiteNotice',
	'Echo',
	'EventLogging',
	'EventStreamConfig',
	'Elastica',
	'Gadgets',
	'GlobalUsage',
	'GlobalBlocking',
	'GlobalCssJs',
	'GlobalUserPage', 
	'GlobalPreferences', 
	'ImageMap',
	'InputBox',
	'Interwiki',
	'LocalisationUpdate',
	'MultimediaViewer',
	'NewUserMessage',
	'Nuke',
	'OATHAuth',
    'MobileFrontend',
	'ParserFunctions',
	'PageViewInfo',
	'Poem',
	'CSS',
	'CheckUser',
	'Renameuser',
	'ReplaceText',
	'Scribunto',
	'SandboxLink',
    'SiteMatrix',
	'SpamBlacklist',
	'SyntaxHighlight_GeSHi',
	'TextExtracts',
	'TorBlock',
	'TitleBlacklist',
	'TemplateStyles',
	'UniversalLanguageSelector',
	'UploadWizard',
	'WikiEditor',] );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;
// Ivestigating
	
